import Head from 'next/head'
import { NextPage } from 'next'

import Header from '@/components/header'
import Hero from '@/components/sections/homepage/hero'
import EngageProspects from '@/components/sections/homepage/engage_prospects'
import Create from '@/components/sections/homepage/create'
import Insights from '@/components/sections/homepage/insights'
import Integrations from '@/components/sections/homepage/integrations'
import ControlUpdates from '@/components/sections/homepage/control_updates'
import PowerAchievements from '@/components/sections/homepage/power_achievements'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flymail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <EngageProspects />
        <Create />
        <Insights />
        <Integrations />
        <ControlUpdates />
        <PowerAchievements />
      </main>
    </>
  )
}

export default Home
