import Head from 'next/head'
import { NextPage } from 'next'

import Header from '@/components/header'
import Hero from '@/components/sections/homepage/hero'
import EngageProspects from '@/components/sections/homepage/engage_prospects/EngageProspects'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Flymail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <EngageProspects />
      </main>
    </>
  )
}

export default Home
